### ISSUE TITLE
Unable to resolve "../../App" from "node_modules\expo\AppEntry.js"

### ISSUE THREAD

**Issue by zyxel648** [GeekyAnts/vue-native-core#183] opened 2019-08-05 13:33 UTC
In console, I just run the following command:
`vue-native init <project name>`
And then, delete App.js file (App.vue file still exists)

```
npm list -g --depth=0

+-- @vue/cli@3.9.3
+-- @vue/cli-init@3.9.0
+-- create-react-native-app@2.0.2
+-- exp@57.2.1
+-- expo-cli@3.0.8
+-- node@11.4.0
+-- npm@6.10.0
+-- react-native-cli@2.0.1
+-- vue-native-cli@0.1.0
+-- webpack@4.29.6
`-- webpack-cli@3.3.0

```
package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-web": "^0.11.4",
    "vue-native-core": "^0.1.0",
    "vue-native-helper": "^0.1.0",
    "vue-native-scripts": "0.0.16"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}
```
Beacause I have problems with installation of vue-native-scripts v.0.1.0  (#182), I added them manually. vue-native-scripts@0.0.16 did not work correncly with RN v.0.59 (expo sdk 34)

In stack trace I see: 
```
The module '../../App' could not be found from 'C:\\sample\\node_moudules\\expo\\AppEntry.js'. Indead, none of these files exist:
* 'C:\\sample\\App(.native||.android.expo.js|.native.expo.js|.expo.js|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.json|.native.expo.json|.expo.json|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx
```

But why it's don't try to resolve module with `vue` extension? 

`metro.config.js`

```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("./vueTransformerPlugin.js"),
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      })
    },
    resolver: {
      sourceExts: [...sourceExts, "vue"]
    }
  };
})();
```

I spent about 3 days trying to solve this issue, but nothing found how to do this.

[Repository](https://github.com/zyxel648/vue-native-sample)

**Comment by Shrekie** [comment] 2019-08-06 12:20
Same.

With yarn I don't have the vue-native-scripts installation issue.

But I'm also getting Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"
Failed building JavaScript bundle.

This is on a totally fresh cli init project

**Comment by ChildishForces** [comment] 2019-08-06 12:49
Same here, I'm guessing it may have something to do with the new version of `vue-native-cli` that went live 4 days ago.

**Comment by zyxel648** [comment] 2019-08-06 14:06
> Same here, I'm guessing it may have something to do with the new version of `vue-native-cli` that went live 4 days ago.

Actually no. I'm already have `vue-native-cli@0.1.0` and `vue-native-core@0.1.0` and I'm trying to use previous versions (0.0.7 and 0.0.8) - get the same error. Also try to use expo sdk v. 33 - same error. It works only on expo sdk 32, but native-base don't. Maybe this error came from expo and metro bundler... who knows. I can't debug js code :(
Finally, I decide to not use vue-native and write with react, beacause vue-native has poor support unfortunately :( Error "Unable to resolve "../../App"" exists more than year and nobody wants to solve this issue 😢

**Comment by ChildishForces** [comment] 2019-08-06 14:20
It's pretty bad that this package is basically unusable then. There's no way to init a new project.

**Comment by tjimenez** [comment] 2019-08-06 15:44
Same for me! :(

**Comment by drmmarsunited** [comment] 2019-08-07 01:44
Also hitting this exact issue when trying to follow `Getting Started` instructions on the Vue native site

**Comment by AnkurDahama** [comment] 2019-08-07 05:09
Same problem with me while following 'Getting started' on vue native site. Tried tweaking some versions but still no luck.

**Comment by Onael23** [comment] 2019-08-07 05:27
`import App from  '../../App.vue'` I tried this and it worked. You have to change the path in the AppEntry.js.

**Comment by AnkurDahama** [comment] 2019-08-07 05:35
Still doesn't work. now getting Unable to resolve "../../App.vue" from "node_modules/expo/AppEntry.js"

**Comment by Onael23** [comment] 2019-08-07 05:42
Okay I see. Send the tree view of your project.

**Comment by AnkurDahama** [comment] 2019-08-07 05:51
<img width="565" alt="Screenshot 2019-08-07 at 8 50 33" src="https://user-images.githubusercontent.com/25076812/62597989-72d90d80-b8f0-11e9-846f-b2293286d433.png">
this is the root folder

**Comment by AnkurDahama** [comment] 2019-08-07 05:52
<img width="999" alt="Screenshot 2019-08-07 at 8 51 39" src="https://user-images.githubusercontent.com/25076812/62598024-99974400-b8f0-11e9-8f14-ffd02a694765.png">
this is my AppEntry.js

**Comment by malisaroj** [comment] 2019-08-07 06:18
But I'm getting Cannot find file: 'App.json' does not match the corresponding name on disk: '.\app.json'.

**Comment by bthomas16** [comment] 2019-08-07 18:40
This began happening to me when I was forced to upgrade Node.js to be compatable with a new Expo version. I had a working project, but after upgrading my Node.js version for Expo compatibility I began seeing this error.

I cleared my entire Node.js cache and got the latest of every dependency. I followed the Vue-native "getting started" documentation. And this error occurs when using command "npm run ios" after simply init-ing a new project

**Comment by ChildishForces** [comment] 2019-08-08 10:30
Any update?

**Comment by zyxel648** [comment] 2019-08-08 10:36
> Any update?

Same error. Even with latest version of expo-cli (3.0.9)

**Comment by ChildishForces** [comment] 2019-08-08 10:37
This is a huge error. We can't even init a new project, so the package is essentially unusable at this version.

**Comment by damferreyra** [comment] 2019-08-08 13:17
Hello there, I don't know if this gonna be helpful, but the latest functional configuration for me is:

package.json:
{
  "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
  "expo": "^32.0.0",
  "react": "16.5.0"
}

app.json:
"sdkVersion": "32.0.0",

Reference SDK 32:
https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough/

With that configuration, I was able to compile a new app created with the latest vue-native CLI.
Sorry about my English :c, have a good day.

**Comment by Shrekie** [comment] 2019-08-08 13:29
Guys, i managed to get newest vue native to work.

In app.json add
"sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]
Inside
"packagerOpts"

![image](https://user-images.githubusercontent.com/16154821/62707197-42c56380-b9f1-11e9-8c6c-a99dd71b0a94.png)

**Comment by ChildishForces** [comment] 2019-08-08 13:42
> I managed to get newest vue native to work.
> 
> In app.json add
> "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]
> Inside
> "packagerOpts"
> 
> ![image](https://user-images.githubusercontent.com/16154821/62707197-42c56380-b9f1-11e9-8c6c-a99dd71b0a94.png)

Hero. Worked for me.

**Comment by zyxel648** [comment] 2019-08-08 13:47
In app.json add
"sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]
Inside
"packagerOpts"

As mentioned by @Shrekie. Thanks 👍

**Comment by NovusTheory** [comment] 2019-08-08 13:50
I probably would still keep this open as this doesn't fix vue-native itself

**Comment by tjimenez** [comment] 2019-08-08 15:27
I've tried for some weeks and I can't even start the clean project.

The last try was adding `"sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]` to app.json file and returns the following error. (clean install)

> UnhandledPromiseRejectionWarning: Error: Cannot find module 'metro/src/reactNativeTransformer'

**Comment by tjimenez** [comment] 2019-08-08 15:42
> I've tried for some weeks and I can't even start the clean project.
> 
> The last try was adding `"sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]` to app.json file and returns the following error. (clean install)
> 
> Resume
> 
> > UnhandledPromiseRejectionWarning: Error: Cannot find module 'metro/src/reactNativeTransformer'
> 
> > Cannot read property 'transformFile' of undefined
> > Failed building JavaScript bundle.


**UPDATE**: Mixing the solution of @damferreyra and @zyxel648 made it work.  Thanks guys.

**Comment by Syltis** [comment] 2019-08-09 07:18
The current latest versions of react and vue worked for me when using the solution @zyxel648 proposed. Great stuff, been stuck on this for a while.

**Comment by Syltis** [comment] 2019-08-09 10:41
I was wrong. This worked for running the app.vue file as project root, but if I add any kind of script to the component I get this error 

`App.vue: tsConsumer.originalPositionFor is not a function`
`Failed building JavaScript bundle.`

No other error-messages are displayed. What does this even mean?

**Comment by damferreyra** [comment] 2019-08-09 10:47
@Syltis 
I used to have the same error
, using  "vue-native-scripts": "0.0.16" (instead of 0.1.0) resolve that issue in my case (with the @zyxel648 solution and the last expo sdk: 34 )

So far everything seems to work ok.

**Comment by anoop-ananthan** [comment] 2019-08-09 11:28
We were not able to use this for our new project because I was not able to run the project

**Comment by ChildishForces** [comment] 2019-08-09 11:43
Seems super bad for a major version release.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Syltis** [comment] 2019-08-09 12:36
@damferreyra  
That actually worked. I am now able to script in App.vue after using the @zyxel648 solution and downgrading 'vue-native-scripts' to 0.0.16. Great stuff, thanks.

**Comment by RishabhKarnad** [comment] 2019-08-09 16:11
@zyxel648 @ChildishForces @Syltis I am unable to reproduce the issue on my end. Are you using the latest version of Expo client? I have tried clearing my cache, resetting the device data, and tested on both iOS and Android.

@Syltis the `tsConsumer.originalPositionFor is not a function` issue is known (#175). It will be fixed with v0.1.1 that should be out within a few hours.

**Comment by ChildishForces** [comment] 2019-08-09 16:14
Latest expo-cli, latest vue-native-cli, latest vue-native-core. Running this on Mac, though don’t know why that’d make a difference.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by drmmarsunited** [comment] 2019-08-10 19:01
After manually adding "vue-native-scripts" pinned to my package.json file at version 0.0.16, I am up and running.  Otherwise receiving issues about MetroBundler.

**Comment by RishabhKarnad** [comment] 2019-08-13 07:43
This is an Expo bug. The workaround mentioned by @Shrekie should work here. Expo seems to be ignoring some of the metro config `resolver` options.

The relevant Expo issues can be found here:
- https://github.com/expo/expo-cli/issues/875
- https://github.com/expo/expo-cli/issues/191

Until those issues are resolved, it seems Expo users will have to use the workaround and modify their `app.json`. I'll update the documentation to reflect this.

**Comment by RishabhKarnad** [comment] 2019-08-13 07:45
> I managed to get newest vue native to work.
> 
> In app.json add
> "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]
> Inside
> "packagerOpts"
> 
> ![image](https://user-images.githubusercontent.com/16154821/62707197-42c56380-b9f1-11e9-8c6c-a99dd71b0a94.png)

Use this until the Expo bug is fixed.

**Closed** 2019-08-13 07:58 UTC

**Comment by Wrufesh** [comment] 2019-08-14 10:40
Simply adding sourceExts in packagerOpts doesnot solve the issue

**Comment by Hiti3** [comment] 2020-07-30 12:25
bump, still not resolved..

**Comment by RishabhKarnad** [comment] 2020-07-30 12:48
@Hiti3 can you please provide a project directory reproducing this with the latest versions of vue-native-core, vue-native-scripts and vue-native-helper (0.1.4)?

**Comment by PixsaOJ** [comment] 2020-11-06 10:12
Still a problem. Just installed expo-cli & vue-native-cli

**Comment by iwasrep** [comment] 2020-12-02 16:59
O que acontece no meu projeto é que eu alterei o arquivo APP, enviando ele para a pasta SRC/APP.... e o expo está buscando ../../APP... quando altero ../src/App no arquivo AppEntry.js localizado em 'node_modules\expo\AppEntrey.js" ele funciona. Como fazer o expo enxergar que eu mudei o arquivo APP?? Detalhe, eu estou usando index.tsx

**Comment by ThomasVeld** [comment] 2020-12-09 10:31
Having the same problem!

**Comment by RishabhKarnad** [comment] 2020-12-09 19:10
To anyone still facing this issue, please add the following information:
- Target platform (iOS / Android / web) -> Please note web is not supported at the moment (#268)
- Development platform (OSX / Linux / Windows) and shell being used

**Comment by prashantpag26** [comment] 2021-02-19 13:10
The error came because our App.js file is path was wrong or we by mistake change put App.js file in another folder.
Check below photo where I put my App.js in routes folder
![image](https://user-images.githubusercontent.com/13349374/108508423-ce57ca00-72e1-11eb-852d-7b3712c4655f.png)

**Comment by wixys** [comment] 2021-04-11 21:27
I nerver can't start a project with vue-native or expo, move to PWA.

**Comment by aacassandra** [comment] 2021-05-22 15:45
2021, vue-native, fresh install can't start. move to ionic-vue3 with capacitor

**Comment by tuannq-0847** [comment] 2021-09-06 01:32
Yeah, 2021 here. It is so fucking frustrating

**Comment by ijoolaie** [comment] 2022-07-09 08:38
> I managed to get newest vue native to work.
> 
> In app.json add "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"] Inside "packagerOpts"
> 
> ![image](https://user-images.githubusercontent.com/16154821/62707197-42c56380-b9f1-11e9-8c6c-a99dd71b0a94.png)

I finally done that.
at first i added the above lines to app.json file but it didn't helped me. after that i wen to this file "../node_modules\expo\AppEntry.js" and edited the import App as "import App from "../../app" then saved it and it worked for me
