### ISSUE TITLE
2 way data binding does not 

### ISSUE THREAD

**Issue by abiodunjames** [GeekyAnts/vue-native-core#157] opened 2019-06-10 12:22 UTC
This worked some 6 months ago when I first tried vue native. I ran into some weird issues now

Steps to reproduce
```
$ vue-native init project
$ yarn add native-base

```

```js
<template>
    <nb-container>
        <nb-header>
            <nb-text>Header</nb-text>
        </nb-header>
        <nb-content>
            <nb-form>
                <nb-item stackedLabel>
                    <nb-label>Link</nb-label>
                    <nb-input v-model="link" v-on:change="getProduct"/>
                </nb-item>              
            </nb-form>
        </nb-content>
    </nb-container>
</template>

<script>
    import Vue from "vue-native-core";
    import {VueNativeBase} from "native-base";
    Vue.use(VueNativeBase);

    export default {
        data() {
            return {
                link: ''
            }
        },
        methods: {
            getProduct() {
                console.log(this.link);
                let url = this.link;
            }
        }
    }
</script>
```
The link in the example above is not binded when user types in something

**Comment by icarter09** [comment] 2019-07-27 03:28
@abiodunjames are you still having this issue?

**Comment by RohanTalip** [comment] 2019-07-28 05:10
@abiodunjames, I don't think NativeBase supports v-model.  It doesn't show up in the code:
https://github.com/GeekyAnts/NativeBase/search?q=v-model&unscoped_q=v-model

The TextInput component in Vue Native does support v-model though:
https://vue-native.io/docs/basic-components.html#TextInput

... and it definitely shows up in the code:
https://github.com/GeekyAnts/vue-native-core/search?q=v-model&unscoped_q=v-model

If you want to use nb-input from NativeBase, then since it extends TextInput from ReactNative:
https://github.com/GeekyAnts/NativeBase/blob/1ca2d20776bbcb31daf85ce4012872e17cb9a0f6/src/basic/Input.js

... you will have to use one of the `onChange`, `onChangeText`, `onSubmitEditing` events or similar.

**Comment by RishabhKarnad** [comment] 2020-04-18 13:34
Closing since this issue is caused by NativeBase not supporting two-way binding, as explained by @RohanTalip. Please open an issue on the NativeBase repo, as the binding would need to be provided in the library's Vue Native plugin.

**Closed by RishabhKarnad** 2020-04-18 13:34 UTC
