### ISSUE TITLE
View shadow

### ISSUE THREAD

**Issue by Peretz30** [GeekyAnts/vue-native-core#96] opened 2018-10-24 12:52 UTC
I want to have box-shadow like this 

![image](https://user-images.githubusercontent.com/27721091/47431383-5d9d5300-d7a4-11e8-8874-107fe23a281a.png)
According https://github.com/styled-components/styled-components/issues/709#issuecomment-409810928
I am trying to use:

```
elevation:4,
shadowOffset: { width: 5, height: 5 },
shadowColor: "grey",
shadowOpacity: 0.5,
shadowRadius: 10,
```

And there are no shadows...

**Comment by Peretz30** [comment] 2018-10-25 06:51
@neeraj-singh47 yes, only I have this issue?

**Comment by Peretz30** [comment] 2018-10-25 11:31
![image](https://user-images.githubusercontent.com/27721091/47497400-9ef43800-d862-11e8-9471-511bb90a3a93.png)
even with margin and padding it's not working

**Comment by icarter09** [comment] 2019-07-26 02:45
@Peretz30 was this issue ever resolved?

**Comment by Peretz30** [comment] 2019-07-29 08:05
@icarter09 nope, this project look like abandoned

**Comment by icarter09** [comment] 2019-07-29 17:45
@Peretz30 I believe that they are getting ready to push out a new release here in the coming days. Were you able to come up with a work around?

**Comment by Peretz30** [comment] 2019-07-30 06:29
@icarter09 No, I switched back to React Native

**Comment by icarter09** [comment] 2019-07-30 12:05
@Peretz30 totally understand. Do you mind closing out this ticket? Thanks.

**Comment by Peretz30** [comment] 2019-07-30 12:21
@icarter09 I am sorry, but why? This issue is not resolved, there are no new versions. So, then contributors will look in issues tab, they can see this open issue and fix it in future releases, but if issue would be closed, they can miss it.

**Comment by icarter09** [comment] 2019-07-30 12:41
> @icarter09 I am sorry, but why? This issue is not resolved, there are no new versions. So, then contributors will look in issues tab, they can see this open issue and fix it in future releases, but if issue would be closed, they can miss it.

My bad. I should have asked if you felt this could be closed or not.

**Comment by didwiz** [comment] 2020-04-18 02:42
@Peretz30 I know this is old, but I also came across this same issue while tinkering with VueNative, and discovered that the shadowbox won't show if you have `overflow:hidden` set on the container.
Apparently this is an old issue with react native and the suggested resolution is to create a parent container element around your main element and attaching the shadow box to that, I can confirm that this works.
This is to help anyone else that comes across this issue.

issues: 
https://github.com/facebook/react-native/issues/449
https://stackoverflow.com/questions/44908580/react-native-shadow-not-appearing
https://react-native.canny.io/feature-requests/p/shadow-does-not-appear-if-overflow-hidden-is-set-on-ios

**Comment by RishabhKarnad** [comment] 2021-03-02 18:54
For anyone still facing the issue, here is a working example:
https://github.com/rahul-mahato/vue-native-box-shadow/blob/main/App.vue

It uses RN stylesheets, since these properties are not supported in the `<style>` tags as of now.

I am closing this issue, but please add a comment in case you still face this issue, along with specific details of the usage. In such a case, the issue could be reopened.

**Closed by RishabhKarnad** 2021-03-02 18:54 UTC
