### ISSUE TITLE
Using React Native UI Frameworks

### ISSUE THREAD

**Issue by ChristopherJohnson25** [GeekyAnts/vue-native-core#248] opened 2020-04-14 15:35 UTC
Are we capable of using React Native UI frameworks with this, for example, React Native UI Kitten. This would be amazing if we could, any code snippets or documentation would be helpful!

**Comment by RishabhKarnad** [comment] 2020-04-18 13:20
Closing as duplicate of #188

**Closed by RishabhKarnad** 2020-04-18 13:20 UTC
