### ISSUE TITLE
How to debug ???

### ISSUE THREAD

**Issue by dainv123** [GeekyAnts/vue-native-core#11] opened 2018-06-13 06:55 UTC
plz help me, How to debug ???

**Comment by chovy** [comment] 2018-06-13 07:07
I'm wondering this too.

**Comment by neeraj-singh47** [comment] 2018-06-13 11:14
@dainv123 We are currently working on this issue. The docs will be updated soon. Until then you can report the issues and we'll help you with the debugging

**Comment by crh225** [comment] 2018-06-19 14:28
console.log(); lol


credits: mjb

**Comment by neeraj-singh47** [comment] 2018-08-21 15:11
For the basic debugging, If you've created project without --no-crna option, then you could refer to `https://docs.expo.io/versions/latest/workflow/debugging` and if project is created using --no-crna options you could refer to https://facebook.github.io/react-native/docs/0.55/debugging

**Comment by jackywongmm** [comment] 2018-10-11 09:31
debugger？aha

**Comment by DannyFeliz** [comment] 2018-10-26 18:11
Waiting for this

**Comment by neeraj-singh47** [comment] 2018-10-29 07:41
@DannyFeliz The source map support has been included. For more info, refer to the above comment. https://github.com/GeekyAnts/vue-native-core/issues/11#issuecomment-414709850

**Comment by dacastro4** [comment] 2019-03-15 03:12
It's been a year and they removed the in-progress label.. I don't think this is happening.

**Comment by mmustafau** [comment] 2019-07-31 21:08
sad, very very sad

**Comment by RishabhKarnad** [comment] 2020-04-18 13:18
Closing this issue since support for source maps has been added. Breakpoints with tools like React Native tools in VS Code have been confirmed to work.

In case of specific issues with debugging, please open new issues in this repository.

**Closed by RishabhKarnad** 2020-04-18 13:18 UTC
Labels: enhancement

**Comment by TheBojda** [comment] 2020-06-07 07:42
You cannot debug VUE files. You can put the breakpoints, but they are not working well. I tried it in Chrome Dev Tools (with Expo), and also with VSCode React Native Tools. My workaround is putting the methods in a separate JS file, and use it as a mixin. Debugging in the separate JS file works like a charm. Here is my example project: https://github.com/TheBojda/VueNativeTodo
