### ISSUE TITLE
Issue: Getting error when I using nested "Component As Prop".

### ISSUE THREAD

**Issue by jawahar273** [GeekyAnts/vue-native-core#252] opened 2020-04-19 07:30 UTC
**Description of the bug**
Hi,
I am integrating graphql mutation in vue-native using `react-apollo` with `formik` for handling form validation. The approach take  by use of `Component as props` on `props.children`. On development this error popups up. 
`Property or method "args" is not defined on instance. but referenced during render.`

**To Reproduce**
##### Packages:
    "graphql": "^15.0.0",
    "graphql-tag": "^2.10.3",
    "react-apollo": "^3.1.5",
    "apollo-boost": "^0.4.7",
    "formik": "^2.1.4",

```js
<mutation :mutation="...">
  <view render-prop-fn="children" arguments="graphqlArgs">
      <formik :initialValues="..."
                    :validationSchema="..."
                    :onSubmit="(values, arg) => onSubmit()" >
            <view render-prop-fn="children" arguments="args"></view>
     </formik>
   </view>
</mutation>
```
> I am 

**What I expected**
Working of mutation and formik.

**Screenshots**
![Screenshot_2020-04-19-12-54-04-052_host exp exponent](https://user-images.githubusercontent.com/7668497/79682097-3ca0ab80-823d-11ea-8934-a2f1a6edd2c2.jpg)

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes
- If you created your project with `vue-native init <projectName>` then yes

**Development platform (please complete the following information):**
 - OS: Ubuntu
 - Shell/terminal: ZSH

**The device on which I run my Vue Native app**
 - Device: Samsung j2
 - OS: Android

**Comment by RishabhKarnad** [comment] 2020-04-26 20:11
Seems like a duplicate of #234

**Closed** 2020-04-29 06:21 UTC
Labels: duplicate
